okta:
  oauth2:
    issuer: https://dev-565937.okta.com/oauth2/default

com.megshan.splitnot.config:
  dynamoDB:
     tableNamePrefix: splitnot-
     accessKeyId:
     secretAccessKey:

logging:
  file:
    name: /var/log/tomcat/tomcat.log

server:
  tomcat:
    accesslog:
      enabled: true
      suffix: .log
      prefix: access
#      file-date-format: .yyyy-MM-dd # file name format
      directory: /var/log/tomcat