plaid:
  plaidurl: https://sandbox.plaid.com

com.megshan.splitnot.config:
  dynamoDB:
     tableNamePrefix: splitnot-
     accessKeyId: AKIAJYGJWFPFOV6BGDXA
     secretAccessKey: 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